lab6/urls.py
from django.urls import path
from . import views

app_name = "lab6"
urlpatterns = [
    path('', views.index, name='index'),
    path('feedback', views.feedback, name='feedback'),
    path('search', views.search, name='search'),
]

vulnerableapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.urls import re_path as url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('lab6.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

lab6/models.py
from django.db import models

# Create your models here.
class BankAccount(models.Model):
    credit_card= models.CharField(max_length=19)
    pin= models.IntegerField()

class Feedback(models.Model):
    message = models.CharField(max_length=100)
    nationalID = models.FileField(null = True, blank = True)

class Branch(models.Model):
    country= models.CharField(max_length=100)
    city= models.CharField(max_length=100)
    street= models.CharField(max_length=100)

lab6/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
import os
from django.db import connection
from .models import Feedback
import js2py

# Create your views here.
def index(request):
    if request.method == 'POST':
        del request.session['username']
        return render(request, 'index.html', {"username" : ""})
    else:
        if request.session.has_key('username'):
            username = request.session['username']
            return render(request,  'index.html', {"username" : username})
        else:
            return render(request, 'index.html', {"username" : ""})

def feedback(request):
    args = {}
    if request.method == 'POST':
        try:
            fileboolean = request.FILES['nationalID']
        except:
            fileboolean = False
        if request.POST.get("message") is not None and fileboolean == True:
            Feedback.objects.create(message=request.POST.get("message"), nationalID=request.FILES['nationalID'])
            return render(request, 'index.html')
        else:
            return render(request, 'feedback.html')
    else:
        return render(request, 'feedback.html')

def search(request):
    if request.method == 'POST':
        if request.POST.get("usersearch") is not None:
            cursor = connection.cursor()
            query = "SELECT city, street FROM lab6_branch WHERE country = '" + str(request.POST.get("usersearch")) +"'"
            branches = cursor.execute(query)
            return render(request, 'search.html', {"branches" : branches , "searched": request.POST.get("usersearch")})
    return render(request, 'search.html', {"searched": ""})

templates/feedback.html

<style>
html {
  background-color: #565656
}

body {
  font-size: 18px;
  font-family: Verdana, Geneva, sans-serif;
  line-height: 1.5;
  color: white;
}

.navbar {
  height: 50px;
  position: fixed;
  width: 100%;
  background-image: linear-gradient(#081829 , #6B798C);
  z-index: 100;
}

.wrapper, .main-wrapper {
  width: 1200px;
  margin: 0 auto;
  padding-left: 30px;
  padding-right: 30px;
  box-sizing: border-box;

}

.navbar .wrapper {
  background-color: rgba(255,255,255,0.1);
}

.main-wrapper {
  font-size: 1.1em;
  padding-top: 80px;
  padding-bottom: 80px;
  padding-right: 80px;
  padding-left: 80px;
  background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
  background-size: cover;
  position: relative;
  z-index: 1;
}

.logo {
  display: inline-block;
}

.logo a {
  line-height: 50px;
  font-size: 1.75em;
  font-weight: bold;
  text-decoration: none;
  color: gold;
}

.mainmenu {
  float: right;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 0;
}

.mainmenu li {
  display: inline;
}

.mainmenu li a {
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
}

.mainmenu li a:hover {
  color: #EDA444;
}

.mainmenu li:not(:last-child) {
  margin-right: 30px;
}

img.myface {
  float: left;
  border-radius: 10px;
  margin-right: 30px;
}

.section:before {
  content: " ";
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: rgba(11,66,131,0.5);
  left: 0px;
  top: 0px;
  z-index: -1;
  border-radius: 10px;
}



.section {
  z-index: 100;
  position: relative;
  padding: 30px;
  vertical-align: top;
  
}

.section h1 {
  margin: 0;
}

.section p {
  position: relative;
}

.section a{
  color: gold;
  font-weight: bold;
  text-decoration: none;
}

.section a:hover {
  color: red;
}

img.ninetysdesk {
  border-radius: 10px;
  margin-left: 30px;
  float: right;
}

img.webtech {
  border-radius: 10px;
  margin-right: 30px;
  float: left;
}

img {
  box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
  background-color: white;
}

td {
  padding: 10px;
  vertical-align: bottom;
}

table {
  float: left;
}

.clearfix {
  clear: both;
  height: 0px;
}
</style>
<html>

<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
  <div class="wrapper">
      <div class="logo"><a href="{% url 'lab6:index' %}">Lab 6</a></div>
      <ul class="mainmenu">
        <li><a href="{% url 'lab6:search' %}">Search Branches</a></li>
        <li><a href="{% url 'lab6:feedback' %}">Give Feedback</a></li>
      </ul>
    </div>
  </nav>
    {% if message != None %}
    <script>alert("{{message}}")</script>
    {% endif %}
    <div class="main-wrapper">
     <div class="section about-section">
      <center><h1>Submit your feedback!</h1></center>
        <div class="feedback-form">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
              <strong>Message:  </strong><br><textarea id="text" name="message" rows="6" cols="50"></textarea><br>
              <br>
              <strong>Front of National ID:  </strong><br><input type="file" name="nationalID"><br>
              <br>
              <button type="submit">Submit</button>
        </form>
      </div>
     </div>
    </div>
</html>

templates/index.html

<style>
html {
  background-color: #565656
}

body {
  font-size: 18px;
  font-family: Verdana, Geneva, sans-serif;
  line-height: 1.5;
  color: white;
}

.navbar {
  height: 50px;
  position: fixed;
  width: 100%;
  background-image: linear-gradient(#081829 , #6B798C);
  z-index: 100;
}

.wrapper, .main-wrapper {
  width: 1200px;
  margin: 0 auto;
  padding-left: 30px;
  padding-right: 30px;
  box-sizing: border-box;

}

.navbar .wrapper {
  background-color: rgba(255,255,255,0.1);
}

.main-wrapper {
  font-size: 1.1em;
  padding-top: 80px;
  padding-bottom: 80px;
  padding-right: 80px;
  padding-left: 80px;
  background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
  background-size: cover;
  position: relative;
  z-index: 1;
}

.logo {
  display: inline-block;
}

.logo a {
  line-height: 50px;
  font-size: 1.75em;
  font-weight: bold;
  text-decoration: none;
  color: gold;
}

.mainmenu {
  float: right;
  list-style: none;
  padding: 0;
  margin: 0;
  font-size: 0;
}

.mainmenu li {
  display: inline;
}

button{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
  padding: 0;
  border: none;
  background: none;
}

button:hover{
  color: #EDA444;
}

.mainmenu li a{
  line-height: 50px;
  text-decoration: none;
  color: black;
  font-size: 18px;
  font-weight: bold;
}

.mainmenu li a:hover {
  color: #EDA444;
}

.mainmenu li:not(:last-child) {
  margin-right: 30px;
}

img.myface {
  float: left;
  border-radius: 10px;
  margin-right: 30px;
}

.section:before {
  content: " ";
  display: block;
  position: absolute;
  width: 100%;
  height: 100%;
  background-color: rgba(11,66,131,0.5);
  left: 0px;
  top: 0px;
  z-index: -1;
  border-radius: 10px;
}



.section {
  z-index: 100;
  position: relative;
  padding: 30px;
  vertical-align: top;
  
}

.section h1 {
  margin: 0;
}

.section p {
  position: relative;
}

.section a{
  color: gold;
  font-weight: bold;
  text-decoration: none;
}

.section a:hover {
  color: red;
}

img.ninetysdesk {
  border-radius: 10px;
  margin-left: 30px;
  float: right;
}

img.webtech {
  border-radius: 10px;
  margin-right: 30px;
  float: left;
}

img {
  box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
  background-color: white;
}

td {
  padding: 10px;
  vertical-align: bottom;
}

table {
  float: left;
}

.clearfix {
  clear: both;
  height: 0px;
}
</style>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<nav class="navbar">
    <div class="wrapper">
        <div class="logo"><a href="{% url 'lab6:index' %}">Lab 6</a></div>
        <ul class="mainmenu">
          <li><a href="{% url 'lab6:search' %}">Search Branches</a></li>
          <li><a href="{% url 'lab6:feedback' %}">Give Feedback</a></li>
        </ul>
      </div>
    </nav>
    
    <div class="main-wrapper">
     <div class="section about-section">
       <h1>Vulnerable Web Application</h1>
       <p>This application contains vulnerabilities. Try to find them.</p>
     </div>
    </div>
    
</html>

templates/search.html

<style>
    html {
      background-color: #565656
    }
    
    body {
      font-size: 18px;
      font-family: Verdana, Geneva, sans-serif;
      line-height: 1.5;
      color: white;
    }
    
    .navbar {
      height: 50px;
      position: fixed;
      width: 100%;
      background-image: linear-gradient(#081829 , #6B798C);
      z-index: 100;
    }
    
    .wrapper, .main-wrapper {
      width: 1200px;
      margin: 0 auto;
      padding-left: 30px;
      padding-right: 30px;
      box-sizing: border-box;
    
    }
    
    .navbar .wrapper {
      background-color: rgba(255,255,255,0.1);
    }
    
    .main-wrapper {
      font-size: 1.1em;
      padding-top: 80px;
      padding-bottom: 80px;
      padding-right: 80px;
      padding-left: 80px;
      background-image:  url("https://i.imgur.com/VGv0QE1.jpg");
      background-size: cover;
      position: relative;
      z-index: 1;
    }
    
    .logo {
      display: inline-block;
    }
    
    .logo a {
      line-height: 50px;
      font-size: 1.75em;
      font-weight: bold;
      text-decoration: none;
      color: gold;
    }
    
    .mainmenu {
      float: right;
      list-style: none;
      padding: 0;
      margin: 0;
      font-size: 0;
    }
    
    .mainmenu li {
      display: inline;
    }
    
    button{
      line-height: 50px;
      text-decoration: none;
      color: black;
      font-size: 18px;
      font-weight: bold;
      padding: 0;
      border: none;
      background: none;
    }
    
    button:hover{
      color: #EDA444;
    }
    
    .mainmenu li a{
      line-height: 50px;
      text-decoration: none;
      color: black;
      font-size: 18px;
      font-weight: bold;
    }
    
    .mainmenu li a:hover {
      color: #EDA444;
    }
    
    .mainmenu li:not(:last-child) {
      margin-right: 30px;
    }
    
    img.myface {
      float: left;
      border-radius: 10px;
      margin-right: 30px;
    }
    
    .section:before {
      content: " ";
      display: block;
      position: absolute;
      width: 100%;
      height: 100%;
      background-color: rgba(11,66,131,0.5);
      left: 0px;
      top: 0px;
      z-index: -1;
      border-radius: 10px;
    }
    
    
    
    .section {
      z-index: 100;
      position: relative;
      padding: 30px;
      vertical-align: top;
      
    }
    
    .section h1 {
      margin: 0;
    }
    
    .section p {
      position: relative;
    }
    
    .section a{
      color: gold;
      font-weight: bold;
      text-decoration: none;
    }
    
    .section a:hover {
      color: red;
    }
    
    img.ninetysdesk {
      border-radius: 10px;
      margin-left: 30px;
      float: right;
    }
    
    img.webtech {
      border-radius: 10px;
      margin-right: 30px;
      float: left;
    }
    
    img {
      box-shadow: 2px 2px 3px 0px rgba(0,0,0,0.8);
      background-color: white;
    }
    
    td {
      padding: 10px;
      vertical-align: bottom;
    }
    
    .clearfix {
      clear: both;
      height: 0px;
    }
    </style>
    <html>
    {% autoescape off %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <nav class="navbar">
      <div class="wrapper">
          <div class="logo"><a href="{% url 'lab6:index' %}">Lab 6</a></div>
          <ul class="mainmenu">
            <li><a href="{% url 'lab6:search' %}">Search Branches</a></li>
            <li><a href="{% url 'lab6:feedback' %}">Give Feedback</a></li>
          </ul>
        </div>
      </nav>
        
        <div class="main-wrapper">
         <div class="section about-section">
            <center><h1>Enter a country to search branches in</h1></center>
            {% if searched != "" %}
            <h2>You've searched for {{searched}}</h2>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <input id="usersearch" name="usersearch"/>
                <button type="submit">Search</button>            
            </form>
                    <table>
            <thead>
            <tr>
                <th>Available Branches</th>
            </tr>
            </thead>
            <tbody>
                <td>
                    {% for branch in branches %}
                    <tr>
                        <td>{{branch}}</td>
                    </tr>
                    {% endfor %}
                </td>
            </tbody>
        </table>
         </div>
        </div>
        {% endautoescape %}

    </html>